### ISSUE TITLE
앱 파일 수정할때만 github action 돌아가게 수정

### ISSUE THREAD

**Issue by minoring** [kookmin-sw/capstone-2021-3#13]
github action 요금 문제도 있어서 app이 수정될때만 github action을 작동하는게 좋아보입니다.

다음과 같은 커밋은 action 이 작동 안하는게 좋겠네요.
https://github.com/kookmin-sw/capstone-2021-3/pull/11

Python에 대한 action은 나중에 추가해도 좋을것같네요.

**Comment by Aqudi** [comment]
아.. 요금이 있는 것은 몰랐네요 얼른 수정해보도록 하겠습니다

**Comment by minoring** [comment]
용어가 헷갈렸네요. 정확히 요금을 내는건 아니고 무료 플랜은 월 ~회 이런 정책이 있습니다!

**Comment by Aqudi** [comment]
아하 다행이네요 ㅎㅎ.. 지갑 열 준비 하고 있었습니다.
수정해서 리뷰 요청드리겠습니다.

**Comment by minoring** [comment]
넵 정리되면 리뷰 보내주시고  커밋에다가 이 이슈번호를 링크걸어주죠.
커밋 메시지에 "#13" 이런걸 추가해주면 링크가 걸립니다.
