### ISSUE TITLE
REST API 개발

### ISSUE THREAD

**Issue by ParkJeongseop** [kookmin-sw/capstone-2021-3#41]
1. 설계를 기반으로 로직 구현
2. MongoDB 연동

**Comment by Aqudi** [comment]
Issue를 좀 더 세분화했으면 좋겠습니다

**Comment by ParkJeongseop** [comment]
> Issue를 좀 더 세분화했으면 좋겠습니다

네 알겠습니다. 큰틀로는 1번2번 자체를 따로 나누었어야 했네요.
